version: "3.7"

services:
  php:
    container_name: ${MICROEVNTQUE_COMPOSE_PROJECT_NAME}_php
    user: 1000:1000
    build:
      context: .docker/php8-dev
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - ./:/packages/EventQueue:rw
    working_dir: /packages/EventQueue
